-- Create the view for the AMAZONREVIEW table
CREATE OR REPLACE VIEW AMAZONREVIEW.AMAZONREVIEW.TEST_VIEW AS
SELECT 
    VERIFIED,
    REVIEWERID,
    ASIN,
    REVIEWERNAME,
    REVIEWTEXT,
    SUMMARY,
    TITLE,
    FEATURE,
    DESCRIPTION,
    PRICE,
    ALSO_BUY,AMAZONREVIEW.AMAZONREVIEW.TEST_VIEW
    BRAND,
    ALSO_BUY_TITLES
FROM 
    AMAZONREVIEW.AMAZONREVIEW.TEST;

-- Confirm the view was created correctly and view sample data
SELECT * FROM AMAZONREVIEW.AMAZONREVIEW.TEST_VIEW LIMIT 10;