# This is secrets.toml

OPENAI_API_KEY = ""
GOOGLE_CSE_ID = ""
GOOGLE_API_KEY = ""
AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""
LLAMA_API = ""
GEMINI_API_KEY = ""

[connections.snowflake]
user = ""
password = ""
account = ""
warehouse = ""
database = ""
role = ""
schema = ""